### ISSUE TITLE
Possible to map from Mac OS host?

### ISSUE THREAD

**Issue by anselanza** [opsxcq/docker-dev-arduino#1]
I have been trying to get this example (and others like it) to work on a Mac OS X host.

On my setup, the Arduino shows up at `/dev/cu.usbmodem144421`
but running
`docker run --rm -it -v "$(pwd):/src" --device=/dev/cu.usbmodem144421 strm/dev-arduino serial`
(slight modification of what is in `functions.sh`, which assumes `/dev/ttyUSB0`), produces the error:

`docker: Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/tty.usbmodem144421": no such file or directory.`

Is device mapping fundamentally different from a Mac OS host, or am I missing something?

**Comment by anselanza** [comment]
Hmm seems like USB device mapping on Docker for Mac might not work at all:

https://forums.docker.com/t/usb-devices-with-private-beta-on-os-x/9951/12
https://github.com/docker/for-mac/issues/900

**Comment by opsxcq** [comment]
Unfortunelly I can't make it work on Mac OSX, but you can create a Linux virtual machine (Vmware/Virtualbox both will work) and attach the device there. I know this is not a good solution, but is the only one that I can figure out using a Mac and Arduino. 

Let me know if you find a better solution to this problem, there are other people in the same situation.

**Comment by anselanza** [comment]
Yeah, VM might be the only way to go. Hopefully Docker for Mac gets some improvements soon.
